### PR TITLE
Quick Edit support

### PR DESCRIPTION
**Pull request by Shade-**
I've been off for a while on SCEditor but now I'm back on it. I wanted to enhance it a little bit with Quick Edit support, as MyBB comes with this feature, and easily sorted it out. I don't know if it should be a core feature but maybe useful for other board's owners: feel free to merge this commit or not.

### CODE REVIEW

**Comment by samclarke** [comment]
Thanks for adding this!

**Comment by martec** [comment]
for me not work...
i tested in localhost...

http://i.imgur.com/4xklGoB.png

**Comment by Shade-** [comment]
My fault, I developed this using my custom theme and didn't checked whether if the loaded textarea has "inlineeditor" class in the Default template too.

Since the ajax-loaded textarea doesn't come with any class attached to it, I can't think about another method to toggle the editor. You have to manually add "inlineeditor" class to your `xmlhttp_inline_post_editor` template, changing:

```
<textarea style="width: 99%; padding: 4px; margin: 0;" rows="12" cols="80" id="quickedit_{$post['pid']}" tabindex="999">{$post['message']}</textarea>
```

To:

```
<textarea style="width: 99%; padding: 4px; margin: 0;" rows="12" cols="80" id="quickedit_{$post['pid']}" tabindex="999" class="inlineeditor">{$post['message']}</textarea>
```

**Comment by martec** [comment]
for me in 1.6.9 this work with class="inlineeditor"... but in 1.6.10 not work...

**Comment by Shade-** [comment]
Strangely, MyBB 1.6.10 doesn't let you update xmlhttp_inline_post_editor template: it keeps on being the default one even if you've edited it. I'd report it to the MyBB team.

---

I've found where's the flaw. The new xmlhttp.php file includes a stripped down version of the core to enhance performances, it seems to load templates from cache (which happens also in 1.6.9<, but within the global.php file). I don't know why it loads the template with sid == -2 though.

**Comment by samclarke** [comment]
Do you have a link to the Quick Edit plugin?

**Comment by Shade-** [comment]
Sure: http://projectxmybb.altervista.org/forum

**Comment by martec** [comment]
solution

change
`$(document).on("focus", ".inlineeditor", function () {`

to

`$(document).on('focus', 'textarea[id*="quickedit_"]', function () {`

and better change this

```
/******************************
     * Source mode option support *
     ******************************/
    if(sceditor_opts.sourcemode)
        $("#message, #signature").sceditor("instance").sourceMode(true); 
```

to

```
    /******************************
     * Source mode option support *
     ******************************/
    if(sceditor_opts.sourcemode) {
        $("#message, #signature").sceditor("instance").sourceMode(true);
        $(document).on('focus', 'textarea[id*="quickedit_"]', function () {

        $(this).sceditor("instance").sourceMode(true);
        $(this).sceditor("instance").focus();
    }); };
```

**Comment by martec** [comment]
and need convert code blelow to scroll to corret position...

```

    quickEditLoaded: function(request, pid)
    {
        if(request.responseText.match(/<error>(.*)<\/error>/))
        {
            message = request.responseText.match(/<error>(.*)<\/error>/);
            if(!message[1])
            {
                message[1] = "An unknown error occurred.";
            }
            if(this.spinner)
            {
                this.spinner.destroy();
                this.spinner = '';
            }
            alert('There was an error performing the update.\n\n'+message[1]);
            Thread.qeCache[pid] = "";
        }
        else if(request.responseText)
        {
            $("pid_"+pid).innerHTML = request.responseText;
            element = $("quickedit_"+pid);
            element.focus();
            offsetTop = -60;
            do
            {
                offsetTop += element.offsetTop || 0;
                element = element.offsetParent;
            }
            while(element);

            scrollTo(0, offsetTop);
        }
        if(this.spinner)
        {
            this.spinner.destroy();
            this.spinner = '';
        }
    },

```

**Comment by Shade-** [comment]
True indeed martec. I've improved the code so it should work fine now, even on 1.6.10. Also, now it scrolls to the editor with an elegant animation.

**Comment by martec** [comment]
very thanks...
now all ok...

**Pull request merged**
