### PR TITLE
Update jscripts/sceditor/jquery.sceditor.mybb.helper.js

### PR DESCRIPTION
**Pull request by charafweb**
Added RTL and LTR icons to the editor toolbar

### CODE REVIEW

**Comment by samclarke** [comment]
Does MyBB support [rtl] and [ltr] BBCodes?

**Comment by charafweb** [comment]
I forget about to check if mybb support those tags. No, mybb doesn't support theme...sorry for this mistake...
I was using a class_parser.php file that I edited so mybb support those tags.

**Comment by samclarke** [comment]
Ah thought it didn't. :)

Thinking about it, there should really be a way to customise the toolbar without editing the plugin. I'll add an issue so I remember to add an option to do it.

**Comment by charafweb** [comment]
Good idea. Good luck

**Pull request closed without merging**
